### ISSUE TITLE
Multi-pages

### ISSUE THREAD

**Issue by rafacesar** [rafacesar/simplehar#12]
Support multiple pages in one har file

**Comment by soulgalore** [comment]
Hey @rafacesar ,
so finally I will implement simplehar in sitespeed.io :)  Is the multiple pages fixed? Tried http://rafacesar.github.io/simplehar/ but that only seems to show one?

Best
Peter

**Comment by soulgalore** [comment]
ah I see it now, it generates multiple files, that's fine.
